[terminal.shell]
program = "/usr/bin/zsh"
[general]
import = [
    "~/.config/alacritty/themes/themes/vesper.toml"
]
[window]
startup_mode = "Maximized"
opacity = 0.9
decorations = "None"

[font]
size = 11

[cursor.style]
shape = "Beam"
blinking = "Always"

[mouse]
hide_when_typing = true
